baseURL = 'https://your-domain.com/'
languageCode = 'es-es'
theme = 'LoveIt'
copyright = "2025"
# Configuración de menús
[[menu.main]]
  weight = 1
  identifier = "posts"
  name = "Posts"
  url = "/posts/"

# [[menu.main]]
#   weight = 2
#   identifier = "tags"
#   name = "Tags"
#   url = "/tags/"

# [[menu.main]]
#   weight = 3
#   identifier = "categories"
#   name = "Categories"
#   url = "/categories/"

# Parámetros específicos del tema LoveIt
[params]
  # site default theme ["auto", "light", "dark"]
  # 网站默认主题 ["auto", "light", "dark"]
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  # 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
  gitRepo = ""
  # which hash function used for SRI, when empty, no SRI is used
  # ["sha256", "sha384", "sha512", "md5"]
  # 哪种哈希函数用来 SRI, 为空时表示不使用 SRI
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = ""
  # date format
  # 日期格式
  dateFormat = "2006-01-02"
  # website title for Open Graph and Twitter Cards
  title = "Blog de Andres Piñeiro"
  # website description for RSS, SEO, Open Graph and Twitter Cards
  description = "Blog de Andres Piñeiro"
  # website images for Open Graph and Twitter Cards
  # 网站图片, 用于 Open Graph 和 Twitter Cards
  images = []
  # Perfil de la página de inicio
  [params.home.profile]
    enable = true
    avatarURL = "/images/icon.png"
    title = "Aquí dejo guardado todo lo que voy aprendiendo para que los demás también puedan aprender y para recordar como hacerlo cuando se me olvide"
    subtitle = "Por favor déjame tu opinión en linkedin o GitHub"

  # Enlaces a redes sociales
  [params.social]
    GitHub = "andrespi97"
    Linkedin = "andrespineirolage"
  [params.author]
    name = "Andrés Piñeiro Lage"
    email = ""
    link = ""
    [params.header.title]
      # URL of the LOGO
      # LOGO 的 URL
      logo = ""
      # title name
      # 标题名称
      name = "Andrés Piñeiro BLOG"
      # you can add extra information before the name (HTML format is supported), such as icons
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = ""
      # whether to use typeit animation for title name
      # 是否为标题显示打字机动画
      typeit = false

  # Footer config
  [params.footer]
    enable = true
    # Custom content (HTML format is supported)
    custom = ""
    # whether to show Hugo and theme info
    # 是否显示 Hugo 和主题信息
    hugo = false
    # whether to show copyright info
    # 是否显示版权信息
    copyright = true
    # whether to show the author
    # 是否显示作者
    author = true
    # site creation time
    # 网站创立年份
    since = 2025
    # ICP info only in China (HTML format is supported)
    # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
    icp = ""
    # license info (HTML format is supported)
    license= ""

[params.page.share]
      enable = false
      X = false
      Threads = false
      Facebook = false
      Linkedin = false
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Flipboard = false
      Weibo = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Diaspora = false
      Mix = false
      Telegram = false